version: '3.4'

services:
  webapp:
    image: marcinkoz52/usersnotebook:webapp
    build: .
    ports:
      - "8080:80"
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"